//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input file not found.
        /// </summary>
        internal static string Exception_Media_Input_File_Not_Found {
            get {
                return ResourceManager.GetString("Exception_Media_Input_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FFmpeg process is not running..
        /// </summary>
        internal static string Exceptions_FFmpeg_Process_Not_Running {
            get {
                return ResourceManager.GetString("Exceptions_FFmpeg_Process_Not_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FFMpeg GZip stream is null.
        /// </summary>
        internal static string Exceptions_Null_FFmpeg_Gzip_Stream {
            get {
                return ResourceManager.GetString("Exceptions_Null_FFmpeg_Gzip_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MediaToolkit.Core.Resources.FFmpeg.exe.gz.
        /// </summary>
        internal static string FFmpegManifestResourceName {
            get {
                return ResourceManager.GetString("FFmpegManifestResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ffmpeg.
        /// </summary>
        internal static string FFmpegProcessName {
            get {
                return ResourceManager.GetString("FFmpegProcessName", resourceCulture);
            }
        }
    }
}
